
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 2;
  public static final int MULTIPLICACION = 21;
  public static final int DIVISION = 22;
  public static final int SUMA = 19;
  public static final int CURVA = 13;
  public static final int ANIMAR = 12;
  public static final int CAFE = 8;
  public static final int CUADRADO = 18;
  public static final int VERDE = 5;
  public static final int ROJO = 4;
  public static final int GRAFICAR = 11;
  public static final int AMARILLO = 6;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int MORADO = 9;
  public static final int NUMERO = 25;
  public static final int PARENTESIS_C = 24;
  public static final int POLIGONO = 17;
  public static final int error = 1;
  public static final int PARENTESIS_A = 23;
  public static final int CIRCULO = 15;
  public static final int AZUL = 3;
  public static final int NEGRO = 10;
  public static final int NARANJA = 7;
  public static final int RECTANGULO = 16;
  public static final int UMINUS = 26;
  public static final int RESTA = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LINEA",
  "AZUL",
  "ROJO",
  "VERDE",
  "AMARILLO",
  "NARANJA",
  "CAFE",
  "MORADO",
  "NEGRO",
  "GRAFICAR",
  "ANIMAR",
  "CURVA",
  "COMA",
  "CIRCULO",
  "RECTANGULO",
  "POLIGONO",
  "CUADRADO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "NUMERO",
  "UMINUS"
  };
}

